src/models.py
from datetime import datetime

from flask_login import UserMixin
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash

from src.app import db, login #potrzebujemy do stworzenia klas User i Water

from sqlalchemy.inspection import inspect


class User(db.Model, UserMixin):
    _authenticated = True #wszyscy użytkownicy są z góry authenticated
    __tablename__ = 'user_table'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.Unicode(128), nullable=False, unique=True)
    firstname = db.Column(db.Unicode(128))
    lastname = db.Column(db.Unicode(128))
    password = db.Column(db.Unicode(128))
    is_active = db.Column(db.Boolean, default=True)
    is_admin = db.Column(db.Boolean, default=False)
    is_anonymous = False

    def get_id(self):
        return self.id

    def __str__(self):
        return self.email

    def __init__(self, *args, **kw):
        super(User, self).__init__(*args, **kw)
        self._authenticated = True

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_authenticated(self):
        return self._authenticated


def serialize_object(obj, fields): #serializacja - zamiana obiektu na słownik (json)
    d = {}
    for key in [e for e in inspect(obj).attrs.keys() if e in fields]:
        obj_atr = getattr(obj, key)
        if isinstance(obj_atr, datetime):
            d[key] = obj_atr.strftime('%Y-%m-%d %H:%M')
        elif isinstance(obj_atr, User):
            d[key] = str(obj_atr) #odnosi się do magicznej funkcji def __str__
        else:
            d[key] = obj_atr
    return d


class Water(db.Model):
    __tablename__ = 'water_table'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    quantity = db.Column(db.Integer)  # ilosc_wody
    user_id = db.Column(db.Integer, db.ForeignKey('user_table.id'))
    user = relationship('User', foreign_keys=user_id)
    timestamp = db.Column(db.DateTime)

    def serialize(self):
        d = serialize_object(self, ['quantity', 'user', 'timestamp'])
        return d


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

src/forms.py
from flask_wtf import FlaskForm
import wtforms as f
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from wtforms.fields.html5 import EmailField

from src.models import User


class LoginForm(FlaskForm):
    email = EmailField('Email address', [DataRequired(), Email()])
    password = f.PasswordField('Password', validators=[DataRequired()])
    remember_me = f.BooleanField('Remember me')
    display = ['email', 'password']


class WaterForm(FlaskForm):
    quantity = f.IntegerField('Water quantity (in ml)', validators=[DataRequired()])
    display = ['quantity']


class RegistrationForm(FlaskForm):
    email = f.StringField('Email', validators=[DataRequired(), Email()])
    password = f.PasswordField('Password', validators=[DataRequired()])
    password2 = f.PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = f.SubmitField('Register')

src/app.py
from decouple import config #decouple wyciąga zmienne z pliku .env
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__) #instancja aplikacji
login = LoginManager(app) #zmienna do logowania

login.login_view = 'login' #definicja widoku logowania
FULL_DB_URL = f"postgresql+psycopg2://" \
              f"{config('DB_USERNAME', default='postgres')}:" \
              f"{config('DB_PASSWORD', default='12345')}@" \
              f"{config('DB_URL', default='127.0.0.1:5432')}/" \
              f"{config('DB_NAME', default='watercontroller')}" #pełna ścieżka do bazy danych
app.config['WTF_CSRF_SECRET_KEY'] = config('WTF_CSRF_SECRET_KEY', default='secret1')
app.config['SECRET_KEY'] = config('SECRET_KEY', default='secret2')
app.config['SQLALCHEMY_DATABASE_URI'] = FULL_DB_URL
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['UPLOAD_FOLDER'] = 'uploads'
db = SQLAlchemy(app)
login_manager = LoginManager(app)


@login_manager.user_loader
def load_user(id):
    from src.models import User #ten import musi być w tym miejscu żeby nie zapętlać się z innymi importami
    return User.query.filter_by(id=id).first()


def register_blueprints(): #unikamy zapętlenia importów
    from src.views import home
    app.register_blueprint(home)


if __name__ == '__main__':
    register_blueprints()
    db.init_app(app)
    app.run(debug=True)

src/views.py
import os
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, send_from_directory
from flask_login import (login_user, logout_user, current_user)

from src.app import db, app
from src.forms import LoginForm, RegistrationForm, WaterForm
from src.models import User, Water
from src.utils import list2pdf

home = Blueprint('home', __name__)


@home.route('/') #dekorator
def index():
    return render_template("index.html", user=current_user)


@home.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.user_profile'))

    form = LoginForm() #else
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first() #sprawdzenie czy istnieje użytkownik o danym mailu
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password')
            return redirect(url_for('home.login'))  # url_for -> domena + ściezka, np. 127.0.0.1:5000/login

        login_user(user, remember=form.remember_me.data) #else
        return redirect(url_for('home.user_profile'))
    return render_template('login.html', form=form, user=current_user)


@home.route("/logout")
def logout():
    logout_user()
    return redirect('/')


@home.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('home.login'))

    return render_template('registration.html', title='Register', form=form, user = current_user)


@home.route('/profile', methods=['GET', 'POST'])
def user_profile():
    form = WaterForm()
    if form.validate_on_submit():
        water = Water(quantity=form.quantity.data,
                      user=current_user,
                      timestamp=datetime.now())
        db.session.add(water)
        db.session.commit()
        flash('Congratulations! Your data was successfully added.')
        return redirect(url_for('home.user_profile'))

    water_list = Water.query.filter_by(user_id=current_user.id)
    sum_of_quantities = 0
    for water in water_list:
        sum_of_quantities += water.quantity
    return render_template('profile.html', title='User Profile', water_list=water_list, form=form,
                           user=current_user, sum_of_water=sum_of_quantities)


@home.route('/generate_raport', methods=['GET'])
def generate_raport():
    water_list = Water.query.filter_by(user_id=current_user.id)
    water_json = list2pdf([water.serialize() for water in water_list]) #tworzymy słownik dla każdego obiektu z listy
    uploads = os.path.join(app.root_path, app.config['UPLOAD_FOLDER']) #tworzymy ścieżkę do folderu z raportem
    with open(os.path.join(uploads, 'raport.pdf'), 'wb+') as f: #otwieranie pliku
        f.write(water_json) #zapis do pliku pdf
    return send_from_directory(directory=uploads, filename='raport.pdf', as_attachment=True) #plik jest automatycznie pobierany

src/templates/base.html
<!--szablon wykorzystywany przez inne podstrony-->
<!DOCTYPE html>
<html lang="en">
  <head>
<!--    zbiór elementów, wykorzystywany do budowania strony-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title>Water Controller - {% block title %} 
        {% endblock %}
    </title>
  </head>
  <body>
<!--  nawigacja-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('home.index') }}">Water Controller</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

<a class="nav-link" href="{{ url_for('home.register') }}">Register</a>
{% if user.is_authenticated %}
    <a class="nav-link" href="{{ url_for('home.logout') }}">Log out</a>
    <a class="nav-link" href="{{ url_for('home.user_profile') }}">My profile</a>
{% else %}
    <a class="nav-link" href="{{ url_for('home.login') }}">Sign in</a>
{% endif %}

  </div>
</nav>
  <div class="container">
    {% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <p style="color: red;">{{ message }}</p>
    {% endfor %}
  {% endif %}
{% endwith %}
    {% block content %}

    {% endblock %}
  </div>
  </body>
</html>

src/templates/index.html
{% extends 'base.html' %} 
{% block title %} 
Main page
{% endblock %}
{% block content %}

<div class="text-center">
<h1>Water Controller</h1>
The human body is made up of approximately 60% water, the brain is 75% water and our blood is 83%. We are continually losing water over the day through urine, sweat and in our breath as vapour.
This water has to be replaced, as the body cannot store water. In fact, the human body can last weeks without food but only days without water; water is absolutely essential to life.
Water is important to remove waste products from the body and to help the body process and get rid of any toxins. The kidneys require plenty of water to filter and remove impurities and waste from the blood. The liver, your body’s main detoxification organ also needs water to neutralise harmful substances so they can be safely removed from the body.
Adding a squeeze of lemon to your water will further stimulate the liver’s detoxification pathways.
This application will help you to notice how much water you are drinking daily. And also to generate a raport in json format about your drinking water history.
</div>
<div class="text-center">
<button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('home.register') }}'">Register</button>
<button type="button" class="btn btn-secondary" onclick="location.href='{{ url_for('home.login') }}'">Sign in</button>
</div>
{% endblock %}
  

src/templates/login.html
{% extends 'base.html' %} 
{% block title %} 
Log in
{% endblock %}
{% block content %}
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <dl>
     {% for field in form.display %}
     <dt>{{ form[field].label }}</dt>
     <dd>{{ form[field]() }}</dd>
       {% if form[field].errors %}
          {% for e in form[field].errors %}
           <p class="help-block">{{ e }}</p>
          {% endfor %}
       {% endif %}
     {% endfor %}
    </dl>
    <p>
    <input type=submit value="Login">
  </form> 
{% endblock %}
  

src/templates/profile.html
{% extends 'base.html' %} 
{% block title %} 
User profile
{% endblock %}
{% block content %}

<div class="text-center">
<h1>My profile</h1>
<table style="width:100%">
  <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Quantity</th>
  </tr>
      {% for row in water_list|sort(attribute='timestamp', reverse = True) %}
    <tr>
    <td>{{ row.timestamp.strftime('%Y-%m-%d') }}</td>
    <td>{{ row.timestamp.strftime('%H:%M') }}</td>
    <td>{{ row.quantity }}</td>
    </tr>
      {% endfor %}

</table>
    <br>
    <h2> You drunk </h2>
    <p>
        {{ sum_of_water }}<br>
        <button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('home.generate_raport') }}'">Generate raport</button>
{#        <button type="submit" onclick="window.open('file.doc')">Download!</button>#}
<h3>Register water intake</h3>
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <dl>
     {% for field in form.display %}
     <dt>{{ form[field].label }}</dt>
     <dd>{{ form[field]() }}</dd>
       {% if form[field].errors %}
          {% for e in form[field].errors %}
           <p class="help-block">{{ e }}</p>
          {% endfor %}
       {% endif %}
     {% endfor %}
    </dl>
    <p>
    <input type=submit value="Submit">
  </form>
</div>
<div class="text-center">
</div>
{% endblock %}
  

src/templates/registration.html
{% extends 'base.html' %} 
{% block title %} 
Register
{% endblock %}
{% block content %}
<h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
<!--        //generowanie i zwracanie tockenu-->
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}